import {useEffect,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {community,readSession,type User} from './client';
import './admin-accounts.css';
import EmailSettings from './EmailSettings';
import DriveSettings from './DriveSettings';
export function logout(){localStorage.removeItem('ease-home-session');location.href='/login/user';}
export default function AccountSettings({updated}:{updated:(user:User)=>void}){
 const [user,setUser]=useState<(User & {mobile:string})|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{community('account').then(d=>setUser({...d.user,mobile:d.user.mobile||''})).catch(e=>setError(e.message));},[]);
 async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget;const values=new FormData(form);if(action==='admin-password'&&values.get('password')!==values.get('confirm')){setError('Passwords do not match.');return;}setBusy(true);setError('');setMessage('');try{const d=await community('account',{action,...Object.fromEntries(values)});setMessage(d.message);if(action==='admin-password'){logout();return;}if(user){const session=readSession();if(session)localStorage.setItem('ease-home-session',JSON.stringify({...session,user}));updated(user);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="cs-accounts"><h2>My profile</h2>{error&&<p className="cs-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{user&&<><form onSubmit={e=>submit(e,'update-profile')}><label>Name<input name="name" required minLength={2} maxLength={120} value={user.name} onChange={e=>setUser({...user,name:e.target.value})}/></label><label>Email<input value={user.email} readOnly/></label><p>Contact the super admin to change your login email.</p><label>Mobile<input name="mobile" type="tel" pattern="\+?[0-9]{7,15}" value={user.mobile} onChange={e=>setUser({...user,mobile:e.target.value})}/></label><button className="cs-primary" disabled={busy}>Save profile</button></form>{user.roles.includes('admin')?<form onSubmit={e=>submit(e,'admin-password')}><h3>Reset super-admin password</h3><label>Current password<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>New password (12–72 characters)<input name="password" type="password" minLength={12} maxLength={72} required autoComplete="new-password"/></label><label>Confirm new password<input name="confirm" type="password" minLength={12} maxLength={72} required autoComplete="new-password"/></label><button className="cs-primary" disabled={busy}>Change password and sign out</button></form>:user.roles.includes('user')&&!user.roles.includes('broker')?<p><Link to="/reset-password">Reset password by email verification</Link></p>:null}</>}{user?.roles.includes('admin')&&<><EmailSettings/><DriveSettings/></>}<button className="cs-link-button" onClick={logout}>Log out</button></section>;
}

