import {useEffect,useState} from 'react';
import {community,when,type User} from './client';
import Messages from './Messages';
import './admin-accounts.css';
type Enquiry={id:string;post_id:string;name:string;mobile:string;role:string;home_loan:boolean;site_visit:boolean;created_at:string;property:{caption:string;location:string;status:string}|null};
export default function AdminMessages({user,initial}:{user:User;initial?:string}){
 const [tab,setTab]=useState(initial?'chats':'enquiries'),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[items,setItems]=useState<Enquiry[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(tab!=='enquiries')return;let current=true;setLoading(true);setError('');community('contact-enquiries&page='+page).then(d=>{if(current){setItems(d.enquiries);setTotal(d.total);}}).catch(e=>{if(current){setItems([]);setError(e.message);}}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[tab,page,revision]);
 return <section><div className="cs-feed-tabs"><button className={tab==='enquiries'?'active':''} onClick={()=>setTab('enquiries')}>View number enquiries</button><button className={tab==='chats'?'active':''} onClick={()=>setTab('chats')}>Private chats</button></div>{tab==='chats'?<Messages user={user} initial={initial}/>:<div className="cs-accounts"><h2>Property contact requests</h2><p>Contact forms submitted through “View number”. Repeat submissions for the same account and property update the existing enquiry.</p><button className="cs-primary" disabled={loading} onClick={()=>setRevision(n=>n+1)}>Refresh enquiries</button>{error&&<p role="alert" className="cs-error">{error}</p>}{loading?<p role="status">Loading enquiries…</p>:<><p>{total} enquiries</p>{!items.length&&!error&&<p>No contact requests yet.</p>}{items.map(e=><article key={e.id} style={{borderTop:'1px solid #dceaf2',padding:'18px 0'}}><h3>{e.name} · {e.role}</h3><p><a href={'tel:'+e.mobile}>{e.mobile}</a> · {when(e.created_at)}</p><p><strong>{e.property?.caption||'Property unavailable'}</strong></p><p>{e.property?.location} · {e.property?.status}</p><p>Home loan: {e.home_loan?'Requested':'Not requested'} · Site visit: {e.site_visit?'Requested':'Not requested'}</p>{e.property?.status==='approved'&&<a href={'/?post='+encodeURIComponent(e.post_id)}>View property →</a>}<small style={{display:'block'}}>Property ID: {e.post_id}</small></article>)}</>}<div className="cs-account-pager"><button disabled={loading||page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={loading||(page+1)*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</section>;
}
