import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowUpRight,Bookmark,ChevronLeft,ChevronRight,Compass,Eye,Film,Heart,Home,ImagePlus,LogOut,MapPin,MessageCircle,Phone,Plus,Search,Send,ShieldCheck,Wallet as WalletIcon,X} from 'lucide-react';
import {community,inr,readSession,when,type Post,type User} from './client';
import Composer from './Composer';
import Packages from './Packages';
import HeroCarousel,{HeroManager} from './HeroCarousel';
import ContactRequest from './ContactRequest';
import Comments from './Comments';
import {requireSignIn} from './client';
import Messages from './Messages';
import AdminMessages from './AdminMessages';
import Wallet from './Wallet';
import AdminAccounts from './AdminAccounts';
import AccountSettings from './AccountSettings';
import './creator.css';
import './signup.css';
import './property-filters.css';
import OwnerPostActions from './OwnerPostActions';
import DeletedPosts from './DeletedPosts';
import {serviceCategories} from './service-categories';

type Tab='Packages'|'Hero carousel'|'Deleted posts'|'Business network'|'Settings'|'Accounts'|'For you'|'Reels'|'Saved'|'My posts'|'Messages'|'Wallet'|'Review posts'|'Creator wallets';
export default function CreatorApp({admin=false}:{admin?:boolean}){
 const [authReady,setAuthReady]=useState(false);
 const requestVersion=useRef(0);const [revision,setRevision]=useState(0);
 const [user,setUser]=useState<User|null>(null);const [tab,setTab]=useState<Tab>(admin?'Review posts':'For you');const [posts,setPosts]=useState<Post[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [composer,setComposer]=useState(false);const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [authorType,setAuthorType]=useState('');const [intent,setIntent]=useState('');const [serviceCategory,setServiceCategory]=useState('');const [filter,setFilter]=useState('all');const [activeThread,setActiveThread]=useState('');const [params,setParams]=useSearchParams();const [more,setMore]=useState(false);
 useEffect(()=>{if(readSession())community('me').then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setAuthReady(true));else setAuthReady(true);},[]);
 useEffect(()=>{const timer=setTimeout(()=>setSearch(query.trim()),300);return()=>clearTimeout(timer);},[query]);
 async function load(append=false){
  const version=++requestVersion.current;setLoading(true);setError('');try{let resource=tab==='My posts'?'mine':tab==='Saved'?'saved':tab==='Review posts'?'review&status='+filter:'feed';if(params.get('post')&&resource==='feed')resource+='&post='+encodeURIComponent(params.get('post')!);if(append&&posts.length)resource+=tab==='Review posts'?'&offset='+posts.length:'&before='+encodeURIComponent(posts[posts.length-1].created_at);resource+='&'+new URLSearchParams({search,authorType,intent:tab==='Business network'?'':intent,postType:tab==='Business network'?'service':'',serviceCategory:tab==='Business network'?serviceCategory:''});const d=await community(resource);if(version!==requestVersion.current)return;setPosts(p=>append?[...p,...d.posts.filter((x:Post)=>!p.some(y=>y.id===x.id))]:d.posts);setMore(resource.startsWith('review')?d.posts.length===60:d.posts.length===30&&resource.startsWith('feed'));}catch(e){if(version===requestVersion.current){setError((e as Error).message);if(!append)setPosts([]);}}finally{if(version===requestVersion.current)setLoading(false);}
 }
 useEffect(()=>{if(!['Packages','Hero carousel','Deleted posts','Settings','Accounts','Wallet','Creator wallets','Messages'].includes(tab))void load();return()=>{requestVersion.current++;};},[tab,filter,params,revision,search,authorType,intent,serviceCategory]);
 function choose(next:Tab){if(!user&&!['For you','Reels','Business network'].includes(next)){setNotice('Sign in to open your '+next.toLowerCase()+'.');return;}setParams({});setTab(next);setNotice('');setError('');}
 function create(){if(!user){setNotice('Sign in to create your first property post.');return;}setComposer(true);}
 async function message(post:Post){if(!user){requireSignIn(post.id);return;}try{const d=await community('',{action:'thread',post:post.id});setActiveThread(d.id);setTab('Messages');setNotice('');}catch(e){setNotice((e as Error).message);}}
 const visible=posts.filter(p=>(tab!=='Reels'||p.media.some(m=>m.mime.startsWith('video'))));
 const navigation: [Tab,typeof Home][] = admin?[['Packages',WalletIcon],['Hero carousel',ImagePlus],['Accounts',ShieldCheck],['Review posts',ShieldCheck],['Creator wallets',WalletIcon],['Business network',Home],['For you',Compass],['Messages',MessageCircle],['Deleted posts',ShieldCheck],['My posts',ImagePlus],['Settings',ShieldCheck]]:[['For you',Home],['Business network',Home],['Reels',Film],['Messages',MessageCircle],['Saved',Bookmark],['My posts',ImagePlus],['Wallet',WalletIcon],['Settings',ShieldCheck]];
 if(!admin&&user?.roles.includes('broker')&&user.account_category!=='builder')navigation.splice(navigation.findIndex(([name])=>name==='Wallet'),0,['Packages',WalletIcon]);
 return <div className="cs-app"><header className="cs-topbar"><Link to="/" className="cs-brand"><span><Home size={22}/></span>easehome<span className="cs-dot">●</span></Link><label className="cs-top-search"><Search size={18}/><input aria-label="Search posts" placeholder="Search property details or location" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌕</kbd></label><div className="cs-top-actions"><span className="cs-community-label">PROPERTY. BUT MAKE IT SOCIAL.</span><button className="cs-primary" onClick={create}><Plus size={17}/>Create post</button>{user?<button className="cs-avatar" aria-label="Open account settings" onClick={()=>choose('Settings')}>{user.name.slice(0,1)}</button>:<Link className="cs-primary cs-auth-entry" to="/signin">LOGIN</Link>}</div></header>
 {tab==='For you'&&authReady&&(!user||(user.roles.includes('user')&&!user.roles.includes('admin')&&!user.roles.includes('broker')))&&<HeroCarousel/>}<div className="cs-shell"><aside className="cs-nav"><span className="cs-section-label">{admin?'SUPER ADMIN':'YOUR DAILY DISCOVERY'}</span><nav>{navigation.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>choose(name)}><Icon size={21}/><span>{admin&&name==='Messages'?'Message Notifications':name}</span>{name==='Reels'&&<small>PLAY</small>}</button>)}{user&&<button className="cs-menu-logout" onClick={()=>{localStorage.removeItem('ease-home-session');location.href='/';}}><LogOut size={21}/><span>Logout</span></button>}</nav><button className="cs-create-side" onClick={create}><Plus size={18}/>Share your space</button><div className="cs-nav-bottom"><div className="cs-community-symbol"><Home/><Heart size={17}/></div><strong>Spaces bring us together.</strong><p>Your home has a story.<br/>Let someone fall in love with it.</p>{user?<button onClick={()=>{localStorage.removeItem('ease-home-session');location.href='/';}}><LogOut size={14}/> Sign out</button>:<Link to="/login/user">Join the community →</Link>}{user?.roles.includes('admin')&&<Link to={admin?'/':'/portal/admin'}>{admin?'Back to community':'Super admin'}</Link>}</div></aside>
 <main className={'cs-main '+(['Packages','Hero carousel','Deleted posts','Settings','Accounts','Messages','Wallet','Creator wallets'].includes(tab)?'cs-wide':'')}><div className="cs-page-heading"><div><small>{admin?'COMMUNITY CONTROL ROOM':'NOT JUST A PLACE. A POSSIBILITY.'}</small><h1>{tab==='Packages'?'Plans for property professionals.':tab==='Hero carousel'?'Manage your homepage highlights.':tab==='Deleted posts'?'Deleted posts and audit history.':tab==='Business network'?'Find local businesses and services.':tab==='Settings'?'Your profile and security.':tab==='Accounts'?'People and permissions.':tab==='For you'?'Your next chapter is in the feed.':tab==='Reels'?'A little scroll. A whole new view.':tab==='My posts'?'Your stories. Your spaces.':tab==='Saved'?'Keep the ones you love.':tab==='Review posts'?'Review. Protect. Publish.':tab==='Messages'?'Let’s talk spaces.':tab==='Creator wallets'?'Reward the people behind the posts.':'Good stories deserve a little more.'}</h1></div><span className="cs-live-dot"><i/>{admin?'Admin workspace':'The property community'}</span></div>
 {(notice||error)&&<div className={error?'cs-alert error':'cs-alert'} role="status"><span>{error||notice}</span><button aria-label="Dismiss notification" onClick={()=>{setError('');setNotice('');}}><X size={16}/></button></div>}
 {admin&&!user?<div className="cs-empty"><ShieldCheck size={40}/><h2>Super admin sign-in required</h2><Link className="cs-primary" to="/login/admin">Sign in as admin</Link></div>:admin&&!user?.roles.includes('admin')?<div className="cs-empty"><ShieldCheck/><h2>This workspace is for super admins.</h2><Link to="/">Return to your feed</Link></div>:<>
 {tab==='Packages'?<Packages admin={admin}/>:tab==='Hero carousel'?<HeroManager/>:tab==='Deleted posts'?<DeletedPosts/>:tab==='Settings'?<AccountSettings updated={setUser}/>:tab==='Accounts'?<AdminAccounts/>:tab==='Messages'&&user?(admin?<AdminMessages user={user} initial={activeThread}/>:<Messages user={user} initial={activeThread}/>):tab==='Wallet'?<Wallet/>:tab==='Creator wallets'?<Wallet admin/>:<>
 {!admin&&tab==='For you'&&<><button className="cs-composer-prompt" onClick={create}><span className="cs-avatar">{user?.name.slice(0,1)||'+'}</span><span>What makes your space special?</span><ImagePlus size={20}/><Film size={20}/><span className="cs-prompt-button">Post it</span></button><div className="cs-feed-tabs"><button className="active">For you</button><button onClick={()=>choose('Reels')}>Video stories</button><button onClick={()=>choose('Saved')}>Your collection</button><span>Discover something worth sharing <ArrowUpRight size={14}/></span></div></>}
 <div className="cs-property-filters"><label>Search properties<input aria-label="Search property details" maxLength={100} placeholder="Apartment, Chennai, sale…" value={query} onChange={e=>{setParams({});setQuery(e.target.value);}}/></label><label>Posted by<select aria-label="Posted by" value={authorType} onChange={e=>{setParams({});setAuthorType(e.target.value);}}><option value="">Everyone</option>{['user','broker','dealer','builder'].map(role=><option key={role} value={role}>{role==='user'?'User':role[0].toUpperCase()+role.slice(1)}</option>)}</select></label>{tab==='Business network'?<label>Service category<select aria-label="Service category" value={serviceCategory} onChange={e=>setServiceCategory(e.target.value)}><option value="">All services</option>{serviceCategories.map(c=><option key={c}>{c}</option>)}</select></label>:<label>Property purpose<select aria-label="Property purpose" value={intent} onChange={e=>{setParams({});setIntent(e.target.value);}}><option value="">Sale & rent</option><option value="Sell">For sale</option><option value="Rent">For rent</option></select></label>}<button onClick={()=>{setQuery('');setSearch('');setAuthorType('');setIntent('');setServiceCategory('');setParams({});}}>Clear filters</button></div>
 {tab==='Review posts'&&<div className="cs-feed-tabs">{['all','pending','approved','rejected'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f==='all'?'All posts':f==='pending'?'Awaiting review':f==='approved'?'Published':'Rejected'}</button>)}<span>All creators: customers, dealers, brokers and builders. Only approved posts are public.</span></div>}
 {tab==='My posts'&&<div className="cs-review-note"><ShieldCheck/><p>Only approved posts appear in the feed. Pending and rejected posts are visible to you and the super admin.</p></div>}
 {loading&&!posts.length?<div className="cs-skeleton" aria-label="Loading posts"><div/><div/><div/></div>:visible.length?<div className={'cs-posts '+(tab==='Reels'?'reels':'')}>{visible.map(post=><PostCard key={post.id} post={post} user={user} manage={tab==='My posts'} review={tab==='Review posts'} onMessage={()=>message(post)} notify={setNotice} refresh={()=>load()}/>)}</div>:<div className="cs-launch"><div className="cs-launch-art"><div className="cs-art-card"><Home size={48}/><span>A SPACE. A STORY.</span><Heart size={24}/></div><span className="cs-art-like"><Heart fill="currentColor" size={18}/> Made for connection</span><span className="cs-art-video"><Film size={21}/> A new point of view</span></div><small>{tab==='Review posts'?'YOU’RE ALL CAUGHT UP':error?'LET’S GET YOU CONNECTED':'EVERY COMMUNITY STARTS WITH A STORY'}</small><h2>{tab==='Saved'?'Your favourites belong here.':tab==='My posts'?'Your first story starts here.':search||authorType||intent?'No properties match these filters.':tab==='Review posts'?'No posts in this queue.':error?'The feed isn’t available yet.':'Be the first to share a space.'}</h2><p>{error?'Please try again once the service is available.':tab==='Reels'?'Approved video stories will appear here.':tab==='Saved'?'Tap the bookmark on a post to keep it close.':'Post a property photo or walkthrough. Once reviewed, it becomes part of the community.'}</p><button className="cs-primary" onClick={error?()=>load():create}>{error?'Try again':'Create a property post'}<Plus size={16}/></button></div>}
 {more&&<button className="cs-load-more" disabled={loading} onClick={()=>load(true)}>{loading?'Loading…':'Discover more posts'}</button>}
 </>}
 </>}</main>
 {!['Packages','Hero carousel','Deleted posts','Settings','Accounts','Messages','Wallet','Creator wallets'].includes(tab)&&<aside className="cs-right"><section className="cs-profile-card"><div className="cs-profile-cover"/><span className="cs-avatar large">{user?.name.slice(0,1)||'e'}</span><h3>{user?.name||'Your space. Your people.'}</h3><p>{user?'Property creator · EASE HOME':'A community built around places we love.'}</p><button onClick={user?()=>choose('My posts'):create}>{user?'Open creator studio':'Share your first story'}<ArrowUpRight size={15}/></button></section><section className="cs-right-panel"><span className="cs-section-label">HOW YOUR STORY GOES LIVE</span><ol><li><ImagePlus/><div><strong>Share your space</strong><p>Photos, a walkthrough, your story.</p></div></li><li><ShieldCheck/><div><strong>Reviewed with care</strong><p>An admin checks every post.</p></div></li><li><Heart/><div><strong>Find your people</strong><p>Likes, shares and real conversations.</p></div></li></ol></section><section className="cs-earn-card"><WalletIcon size={25}/><small>THE CREATOR CORNER</small><h3>Great stories.<br/>Real appreciation.</h3><p>Admin-awarded rewards go straight to your creator wallet.</p><button onClick={()=>choose(admin?'Creator wallets':'Wallet')}>Explore your wallet <ArrowUpRight size={15}/></button></section><p className="cs-right-footer">A little inspiration. A new connection.<br/>A place to call your own.<br/><br/>© {new Date().getFullYear()} EASE HOME</p></aside>}
 </div>{composer&&<Composer close={()=>setComposer(false)} done={()=>{setComposer(false);setTab('My posts');setRevision(n=>n+1);setNotice('Your post is private and awaiting super admin approval.');}}/>}</div>;
}

function PostCard({post,user,review,manage,onMessage,notify,refresh}:{post:Post;user:User|null;review:boolean;manage:boolean;onMessage:()=>void;notify:(s:string)=>void;refresh:()=>void}){
 const [commentsOpen,setCommentsOpen]=useState(false);const viewRecorded=useRef(false);const [contactOpen,setContactOpen]=useState(false);
 const [index,setIndex]=useState(0);const [liked,setLiked]=useState(post.liked);const [saved,setSaved]=useState(post.saved);const [counts,setCounts]=useState(post.counts);const [busy,setBusy]=useState(false);const [call,setCall]=useState('');const [creditKey,setCreditKey]=useState(crypto.randomUUID());const [audit,setAudit]=useState<{id:string;decision:string;note:string;created_at:string}[]|null>(null);const card=useRef<HTMLElement>(null);const media=post.media[index];
 useEffect(()=>{setCounts(post.counts);setLiked(post.liked);setSaved(post.saved);},[post]);
 async function recordView(){if(viewRecorded.current||!user||post.status!=='approved'||post.author_id===user.id||document.visibilityState!=='visible')return;viewRecorded.current=true;try{const d=await community('',{action:'event',post:post.id,kind:'view',active:true});if(typeof d.count==='number')setCounts(c=>({...c,view:d.count}));}catch{viewRecorded.current=false;}}
 useEffect(()=>{
  if(!user||post.status!=='approved'||post.author_id===user.id||!card.current||media?.mime.startsWith('video'))return;
  let timer:ReturnType<typeof setTimeout>|undefined;
  const observer=new IntersectionObserver(entries=>{clearTimeout(timer);if(entries[0].isIntersecting)timer=setTimeout(()=>{void recordView();},5000);},{threshold:.6});observer.observe(card.current);return()=>{clearTimeout(timer);observer.disconnect();};
 },[post.id,post.status,post.author_id,user,media?.id]);
 async function reaction(kind:'like'|'save'){if(!user){requireSignIn(post.id);return;}setBusy(true);try{const active=!(kind==='like'?liked:saved);const d=await community('',{action:'event',post:post.id,kind,active});if(kind==='like'){setLiked(active);setCounts(c=>({...c,like:typeof d.count==='number'?d.count:Math.max(0,c.like+(active?1:-1))}));}else setSaved(active);}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function share(){if(!user){requireSignIn(post.id);return;}try{const url=location.origin+'/?post='+post.id;if(navigator.share)await navigator.share({title:post.caption.slice(0,100),url});else{await navigator.clipboard.writeText(url);notify('Post link copied.');}if(user){const d=await community('',{action:'event',post:post.id,kind:'share',active:true});if(typeof d.count==='number')setCounts(c=>({...c,share:d.count}));}}catch(e){if((e as Error).name!=='AbortError')notify('Sharing is unavailable. Copy this link: '+location.origin+'/?post='+post.id);}}
 async function moderate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await community('',{action:'moderate',post:post.id,status:f.get('decision'),note:f.get('note'),reviewedAll:f.get('reviewed')==='on',safe:f.get('safe')==='on'});notify('Review recorded.');refresh();}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function credit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{await community('',{action:'credit',post:post.id,amount:Math.round(Number(f.get('amount'))*100),note:f.get('note'),key:creditKey});setCreditKey(crypto.randomUUID());form.reset();notify('Reward credited to the creator wallet.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 return <article className="cs-post" ref={card}><header><span className="cs-avatar">{post.author.slice(0,1)}</span><div><strong>{post.author}{post.status==='approved'&&<ShieldCheck size={14}/>}</strong><span>{post.authorType||'Creator'} · <MapPin size={11}/>{post.location} <i>·</i> {when(post.created_at)}</span></div><span className={'cs-badge '+post.status}>{post.status==='approved'?'Reviewed':post.status}</span></header>
 <div className="cs-media">{media?.mime.startsWith('video')?<video key={media.id} src={media.url} controls playsInline preload="metadata" onTimeUpdate={e=>{const video=e.currentTarget;const watched=Array.from({length:video.played.length},(_,i)=>video.played.end(i)-video.played.start(i)).reduce((a,b)=>a+b,0);const rect=video.getBoundingClientRect();if(watched>=5&&rect.top<window.innerHeight&&rect.bottom>0)void recordView();}} onError={()=>notify('This media link may have expired. Refresh the feed to load it again.')}/>:media?<img src={media.url} alt={post.caption.slice(0,150)} loading="lazy"/>:<div className="cs-empty-small">Media unavailable</div>}<span className="cs-media-label">{media?.mime.startsWith('video')?<Film size={12}/>:<ImagePlus size={12}/>} {post.post_type==='service'?post.service_category+' SERVICES':post.intent==='Sell'?'SPACE FOR SALE':'SPACE FOR RENT'}</span>{post.media.length>1&&<><span className="cs-media-count">{index+1} / {post.media.length}</span><button className="cs-media-prev" aria-label="Previous media" onClick={()=>setIndex((index+post.media.length-1)%post.media.length)}><ChevronLeft/></button><button className="cs-media-next" aria-label="Next media" onClick={()=>setIndex((index+1)%post.media.length)}><ChevronRight/></button></>}</div>
 <div className="cs-post-body"><div className="cs-social-actions"><button title="Like" aria-label="Like post" aria-pressed={liked} disabled={busy||post.status!=='approved'} onClick={()=>reaction('like')}><Heart fill={liked?'currentColor':'none'}/><span>{counts.like}</span></button><button title="Comment" aria-label="Comment on post" disabled={post.status!=='approved'} onClick={()=>{if(!user){requireSignIn(post.id);return;}setCommentsOpen(v=>!v);}}><MessageCircle/><span>Comment</span></button><button title="Message creator" aria-label="Message creator" disabled={post.status!=='approved'||post.author_id===user?.id} onClick={onMessage}><MessageCircle/></button><button title="Share" aria-label="Share post" disabled={post.status!=='approved'} onClick={share}><Send/><span>{counts.share}</span></button><button title="Save" aria-label="Save post" className="cs-save" aria-pressed={saved} disabled={busy||post.status!=='approved'} onClick={()=>reaction('save')}><Bookmark fill={saved?'currentColor':'none'}/><span>{saved?'Saved':'Save'}</span></button></div><p className="cs-post-caption"><strong>{post.author}</strong> {post.caption}</p><div className="cs-post-tags"><span>#{post.post_type==='service'?'LocalServices':post.intent==='Sell'?'ForSale':'ForRent'}</span><span>#{post.location.replace(/[^\p{L}\p{N}]/gu,'')}</span><span>#EaseHome</span></div><div className="cs-post-meta"><span><Eye size={14}/>{counts.view} unique views</span><strong>{post.post_type==='service'?(Number(post.price)===0?'Request a quote':'From '+inr(Number(post.price)*100)):inr(Number(post.price)*100)}{post.post_type!=='service'&&post.intent==='Rent'&&<small> / month</small>}</strong></div><div className="cs-post-connect"><button onClick={onMessage} disabled={post.status!=='approved'||post.author_id===user?.id}><MessageCircle size={16}/>Message creator</button>{call?<a href={'tel:'+call}><Phone size={16}/>{call}</a>:<button disabled={!post.hasPhone||post.status!=='approved'} onClick={()=>{if(!user){requireSignIn(post.id);return;}setContactOpen(true);}}><Phone size={16}/>{post.hasPhone?'View number':'DM to connect'}</button>}</div>{post.status==='rejected'&&<p className="cs-error">Review feedback: {post.review_note}</p>}
 {manage&&post.author_id===user?.id&&<OwnerPostActions post={post} refresh={refresh}/>}
 {commentsOpen&&user&&<Comments post={post.id}/>}
 {contactOpen&&user&&<ContactRequest post={post.id} user={user} close={()=>setContactOpen(false)} done={phone=>{setCall(phone);setContactOpen(false);}}/>}
 {review&&<section className="cs-review-panel"><h3>Post review</h3><p>Inspect all {post.media.length} files, including the full duration of each video. Reject adult content or content unrelated to properties and business services.</p><form onSubmit={moderate}><select name="decision" aria-label="Moderation decision"><option value="approved">Approve and publish</option><option value="rejected">Reject / remove from feed</option></select><textarea name="note" required minLength={5} maxLength={1000} placeholder="Review findings / reason"/><label className="cs-check"><input name="reviewed" type="checkbox" required/>I have reviewed every photo and the entire video.</label><label className="cs-check"><input name="safe" type="checkbox"/>No adult content; this is a relevant property or business-service post.</label><button className="cs-primary" disabled={busy}><ShieldCheck size={15}/>Record decision</button></form><button className="cs-link-button" onClick={async()=>{try{setAudit((await community('post-audit&post='+post.id)).reviews);}catch(e){notify((e as Error).message);}}}>View moderation history</button>{audit&&<ul className="cs-audit">{audit.length?audit.map(a=><li key={a.id}><strong>{a.decision} · {when(a.created_at)}</strong><p>{a.note}</p></li>):<li>No previous reviews.</li>}</ul>}{post.status==='approved'&&<form className="cs-credit-form" onSubmit={credit}><h3>Reward this creator</h3><p>{counts.view} unique views · {counts.like} likes · {counts.share} unique sharers. Verify genuine activity before crediting.</p><label>Credit amount (₹)<input name="amount" type="number" required min="0.01" max="100000" step="0.01"/></label><label>Reward reason<input name="note" required minLength={5} maxLength={500} placeholder="Reviewed engagement reward — September"/></label><button className="cs-primary" disabled={busy}><WalletIcon size={15}/>Credit wallet</button></form>}</section>}
 </div></article>;
}

