import {useEffect,useState,type FormEvent} from 'react';
import {MessageCircle,Send,ArrowLeft} from 'lucide-react';
import {community,when,type User} from './client';
type Thread={id:string;name:string};type Message={id:string;sender_id:string;body:string;created_at:string};
export default function Messages({user,initial}:{user:User;initial?:string}){
 const [threads,setThreads]=useState<Thread[]>([]);const [active,setActive]=useState(initial??'');const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let valid=true;community('threads').then(d=>{if(valid)setThreads(d.threads);}).catch(e=>{if(valid)setError(e.message);});return()=>{valid=false;};},[initial]);
 useEffect(()=>{setActive(initial??'');},[initial]);
 useEffect(()=>{if(!active)return;let valid=true;setMessages([]);const load=()=>community('messages&thread='+active).then(d=>{if(valid){setMessages(d.messages);setError('');}}).catch(e=>{if(valid)setError(e.message);});void load();const id=setInterval(()=>{if(document.visibilityState==='visible')void load();},5000);return()=>{valid=false;clearInterval(id);};},[active]);
 async function send(e:FormEvent){e.preventDefault();if(!text.trim())return;setBusy(true);try{await community('',{action:'message',thread:active,body:text.trim()});setText('');const d=await community('messages&thread='+active);setMessages(d.messages);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="cs-inbox"><aside className={active?'cs-conversations selected':'cs-conversations'}><h2>Your conversations</h2><p>Good connections start with hello.</p>{threads.map(t=><button className={active===t.id?'active':''} onClick={()=>setActive(t.id)} key={t.id}><span className="cs-avatar">{t.name.slice(0,1)}</span><span><strong>{t.name}</strong><small>Property conversation</small></span></button>)}{!threads.length&&<div className="cs-empty-small">Message a creator from their post to start a conversation.</div>}</aside><div className={'cs-chat '+(active?'selected':'')}>{active?<><header><button aria-label="Back to conversations" onClick={()=>setActive('')}><ArrowLeft size={18}/></button><strong>{threads.find(t=>t.id===active)?.name??'Conversation'}</strong><small>Private conversation</small></header><div className="cs-message-list" aria-live="polite">{messages.map(m=><div key={m.id} className={'cs-message '+(m.sender_id===user.id?'mine':'')}><p>{m.body}</p><time>{when(m.created_at)}</time></div>)}{!messages.length&&<p className="cs-help">Say hello and ask about the property.</p>}</div><form onSubmit={send}><input aria-label="Message" placeholder="Write a message…" maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Send message" disabled={busy||!text.trim()}><Send size={19}/></button></form></>:<div className="cs-empty"><MessageCircle size={42}/><h2>A space for real conversations.</h2><p>Choose a conversation or message a property creator.</p></div>}{error&&<p className="cs-error" role="alert">{error}</p>}</div></section>;
}
