import {useState,type FormEvent} from 'react';
import {community,type Post} from './client';
import {serviceCategories} from './service-categories';
export default function OwnerPostActions({post,refresh}:{post:Post;refresh:()=>void}){
 const [images,setImages]=useState<File[]>([]);const [uploaded,setUploaded]=useState<{file:File;id:string}[]>([]);
 const [mode,setMode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{let media:string[]|undefined;if(mode==='edit'&&images.length){media=post.media.filter(m=>m.mime.startsWith('video/')).map(m=>m.id);for(const file of images){const existing=uploaded.find(u=>u.file===file);if(existing){media.push(existing.id);continue;}const ticket=await community('',{action:'upload',mime:file.type,bytes:file.size});const response=await fetch(ticket.url,{method:'PUT',headers:{'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok)throw new Error('Image upload failed. Your post has not been changed.');media.push(ticket.id);setUploaded(items=>[...items,{file,id:ticket.id}]);}}await community('',{media,action:'owner-post',operation:mode,post:post.id,version:post.edit_version??0,reason:data.get('reason'),changes:mode==='edit'?{caption:data.get('caption'),location:data.get('location'),intent:data.get('intent')||'Sell',price:Number(data.get('price')),phone:data.get('phone'),serviceCategory:data.get('serviceCategory')||undefined}:undefined});setMode('');setImages([]);setUploaded([]);refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="cs-review-panel" aria-label="Manage my post"><div style={{display:'flex',gap:20}}><button onClick={()=>{setMode('edit');setImages([]);setError('');}} disabled={busy}>Edit post</button><button onClick={()=>{setMode('delete');setError('');}} disabled={busy}>Delete post</button></div>{mode&&<form onSubmit={submit} key={mode}>{mode==='edit'?<><h3>Edit your post</h3><p>Changes require admin approval before this post becomes public again. Choose new images below to replace the existing photos. Existing videos are retained. Leave this empty to keep the current media.</p><label>Replace photos<input aria-label="Replace post images" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const chosen=Array.from(e.target.files??[]);if(chosen.length+post.media.filter(m=>m.mime.startsWith('video/')).length>8||chosen.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size===0||f.size>50*1024*1024)){setError('Choose JPG, PNG or WebP images under 50 MB each, with at most 8 total files including existing videos.');e.target.value='';setImages([]);return;}setImages(chosen);setError('');}}/></label>{images.length>0&&<div><p>{images.map(f=>f.name).join(', ')}</p><button type="button" disabled={busy} onClick={()=>setImages([])}>Keep existing photos</button></div>}<label>Description<textarea aria-label="Description" name="caption" defaultValue={post.caption} required minLength={10} maxLength={3000}/></label><label>Location / service area<input name="location" defaultValue={post.location} required minLength={2} maxLength={150}/></label>{post.post_type==='service'?<label>Service category<select name="serviceCategory" defaultValue={post.service_category}>{serviceCategories.map(c=><option key={c}>{c}</option>)}</select></label>:<label>Purpose<select name="intent" defaultValue={post.intent}><option>Sell</option><option>Rent</option></select></label>}<label>Price (₹)<input name="price" type="number" defaultValue={post.price} min="0" max="1000000000000" step="0.01" required/></label><label>Contact number<input name="phone" type="tel" defaultValue={post.phone||''} pattern="\+?[0-9]{7,15}"/></label></>:<><h3>Delete this post?</h3><p>It will disappear from the feed and My posts. Its record is retained privately for the super-admin deletion log.</p><label>Reason for deleting<textarea aria-label="Reason for deleting" name="reason" required minLength={5} maxLength={500}/></label></>}{error&&<p className="cs-error" role="alert">{error}</p>}<button className="cs-primary" disabled={busy}>{busy?'Saving…':mode==='edit'?'Save and request approval':'Confirm deletion'}</button><button type="button" disabled={busy} onClick={()=>setMode('')}>Cancel</button></form>}</section>;
}
