import {useEffect,useState,type FormEvent} from 'react';
import {community,inr} from './client';
import './packages.css';
type Plan={id:number;name:string;description:string;price_paise:number|null;duration_days:number;features:string[]};
export default function Packages({admin=false}:{admin?:boolean}){
 const [plans,setPlans]=useState<Plan[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Plan|null>(null);
 async function load(){setPlans((await community('packages')).packages);}
 useEffect(()=>{void load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{await community('',{action:'save-package',id:selected.id,name:f.get('name'),description:f.get('description'),price_paise:f.get('price')===''?null:Math.round(Number(f.get('price'))*100),duration_days:Number(f.get('duration')),features:String(f.get('features')).split('\n').map(s=>s.trim()).filter(Boolean)});await load();setSelected(null);setMessage('Package updated. Brokers and dealers will see the new details.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="cs-packages"><h2>{admin?'Customize broker / dealer packages':'Broker & dealer packages'}</h2><p>{admin?'Edit the three available plans.':'Compare the available plans. Contact the super admin for activation.'} Payments and automatic subscription activation are not enabled.</p>{error&&<p role="alert" className="cs-error">{error}</p>}{message&&<p role="status">{message}</p>}{loading?<p>Loading packages…</p>:<div className="cs-package-grid">{plans.map(p=><article key={p.id}><small>PLAN {p.id}</small><h3>{p.name}</h3><strong>{p.price_paise===null?'Contact admin for pricing':inr(p.price_paise)}</strong><p>{p.duration_days} days</p><p>{p.description}</p><ul>{p.features.map((f,i)=><li key={i}>{f}</li>)}</ul>{admin&&<button className="cs-primary" onClick={()=>setSelected(p)} disabled={busy}>Edit {p.name}</button>}</article>)}</div>}{admin&&selected&&<form className="cs-package-editor" key={selected.id} onSubmit={save}><h3>Edit plan {selected.id}</h3><label>Plan name<input name="name" defaultValue={selected.name} required minLength={2} maxLength={60}/></label><label>Description<textarea name="description" defaultValue={selected.description} maxLength={400}/></label><label>Price (₹, leave blank for contact pricing)<input name="price" type="number" min="0" max="1000000" step="0.01" defaultValue={selected.price_paise===null?'':selected.price_paise/100}/></label><label>Duration in days<input name="duration" type="number" min="1" max="3650" required defaultValue={selected.duration_days}/></label><label>Features (one per line, maximum 20)<textarea name="features" defaultValue={selected.features.join('\n')}/></label><button className="cs-primary" disabled={busy}>Save package</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button></form>}</section>;
}
