import {useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {community} from './client';
import './creator.css';
import './signup.css';
export default function Signup(){
 const [email,setEmail]=useState(''),[category,setCategory]=useState('customer'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[portal,setPortal]=useState(''),[message,setMessage]=useState('');
 const next=new URLSearchParams(location.search).get('next');const returnQuery=next&&/^\/\?post=[a-f0-9-]{36}$/i.test(next)?'?next='+encodeURIComponent(next):'';
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm')){setError('Passwords do not match.');return;}setBusy(true);setError('');try{const d=await community('signup',{name:f.get('name'),email:f.get('email'),mobile:f.get('mobile'),password:f.get('password'),category,company:f.get('company')||''});setEmail(String(f.get('email')||''));setPortal(d.portal);setMessage(d.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="cs-app cs-signup-page"><section className="cs-signup-card"><Link to="/">← Back to the feed</Link><nav className="cs-auth-tabs" aria-label="Account access"><Link to={'/signin'+returnQuery}>Sign in</Link><Link aria-current="page" to={'/signup'+returnQuery}>Sign up</Link></nav><h1>Create your EASE HOME account</h1><p>Share properties, discover services and connect with the community.</p>{error&&<p role="alert" className="cs-error">{error}</p>}{portal?<div role="status"><p>{message}</p><p><Link className="cs-primary" to="/verify-email" state={{email,portal,next}}>Verify email / resend OTP</Link></p></div>:<form onSubmit={submit}><label>Account type<select aria-label="Account type" value={category} onChange={e=>setCategory(e.target.value)}><option value="customer">User</option><option value="broker">Broker</option><option value="dealer">Dealer</option><option value="builder">Builder</option></select></label><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={120}/></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Mobile number<input name="mobile" type="tel" autoComplete="tel" required pattern="\+?[0-9]{7,15}" placeholder="+919876543210"/></label>{category!=='customer'&&<label>Business name<input name="company" required minLength={2} maxLength={200} autoComplete="organization"/></label>}<label>Password<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><small>Use at least 12 characters. Maximum 72 UTF-8 bytes.</small><label>Confirm password<input name="confirm" type="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><p>Verify your email before signing in. Email verification does not verify your identity or business; every post still requires admin approval.</p><button className="cs-primary" disabled={busy}>{busy?'Creating account…':'Sign up'}</button></form>}</section></main>;
}

