import {useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {Home,ArrowUpRight,Eye,EyeOff,ShieldCheck,MessageCircle,Heart} from 'lucide-react';
import type {PortalRole} from '../data';
import './creator.css';
import {readApiResponse} from './response';
export default function SocialLogin({role}:{role:PortalRole}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const label=role==='admin'?'Super admin':role==='broker'?'Professional creator':'Creator & viewer';
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,portal:role})});const d=await readApiResponse(r);if(!r.ok||!d.token)throw new Error(d.message||'Unable to sign in.');localStorage.setItem('ease-home-session',JSON.stringify({token:d.token,user:d.user,role,issuedAt:Date.now()}));const next=new URLSearchParams(location.search).get('next');const target=next&&/^\/\?post=[a-f0-9-]{36}$/i.test(next)?next:'/portal/'+role;location.href=target;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="cs-app cs-login"><section className="cs-login-story"><Link className="cs-brand" to="/"><span><Home size={22}/></span>easehome<span className="cs-dot">●</span></Link><div><small>SPACES BRING US TOGETHER.</small><h1>Every home<br/>has a story.<br/><em>What's yours?</em></h1><p>Share a walkthrough. Meet your next buyer.<br/>Find a little inspiration along the way.</p><div className="cs-login-icons"><span><Heart/> Share what you love</span><span><MessageCircle/> Make real connections</span><span><ShieldCheck/> A reviewed community</span></div></div><small>A place to share. A space to belong.</small></section><section className="cs-login-form"><Link to="/" className="cs-link-button">← Back to the feed</Link><div><span className="cs-section-label">{label.toUpperCase()} ACCESS</span><h2>Good to see you here.</h2><p>Sign in and find your people.</p><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Password<div className="cs-password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} autoComplete="current-password"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{error&&<p role="alert" className="cs-error">{error}</p>}<button className="cs-primary" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowUpRight size={18}/></button></form>{role==='user'&&<p><Link to="/reset-password">Forgot password? Verify by email</Link></p>}<div className="cs-login-switch">Choose your portal<Link to="/login/user">Creator / viewer</Link><Link to="/login/broker">Professional</Link><Link to="/login/admin">Super admin</Link></div></div></section></main>;
}
