import {useEffect,useState,type FormEvent} from 'react';
import {ArrowDownLeft,ArrowUpRight,Wallet as WalletIcon,ShieldCheck} from 'lucide-react';
import {community,inr,when} from './client';
type Entry={id:string;user_id:string;amount_paise:number;kind:string;note:string;created_at:string};
type Withdrawal={id:string;user_id:string;amount_paise:number;bank_last4:string;status:string;reference?:string;created_at:string};
type Data={balance:number;ledger:Entry[];withdrawals:Withdrawal[];people?:{id:string;name:string}[];wallets:{user_id:string;balance_paise:number}[]};
export default function Wallet({admin=false}:{admin?:boolean}){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [key,setKey]=useState(crypto.randomUUID());const [bank,setBank]=useState<{id:string;holder:string;account:string;ifsc:string}|null>(null);
 async function load(){try{setData(await community(admin?'admin-wallet':'wallet'));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[admin]);
 async function withdraw(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setError('');try{await community('',{action:'withdraw',amount:Math.round(Number(f.get('amount'))*100),holder:f.get('holder'),account:f.get('account'),ifsc:String(f.get('ifsc')).toUpperCase(),key});setKey(crypto.randomUUID());setNotice('Withdrawal requested. The amount is reserved while the admin processes your bank transfer.');form.reset();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function settle(e:FormEvent<HTMLFormElement>,w:Withdrawal){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await community('',{action:'settle',id:w.id,status:f.get('status'),reference:f.get('reference')});setBank(null);setNotice('Withdrawal record updated.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="cs-wallet"><div className="cs-wallet-cover"><div><small>{admin?'CREATOR WALLET LIABILITIES':'YOUR CREATOR WALLET'}</small><h2>{data?inr(data.balance):'—'}</h2><p>{admin?'Total available creator balances':'Available to request for withdrawal'}</p></div><WalletIcon size={58}/></div><p className="cs-help">Rewards are credited by the super admin after reviewing engagement. Views, likes and shares do not automatically create earnings.</p>{error&&<p className="cs-error" role="alert">{error}</p>}{notice&&<p className="cs-success" role="status">{notice}</p>}
 {!admin&&<section className="cs-panel"><h2>Withdraw to your bank</h2><p>Minimum ₹100. Requests are processed manually by the admin.</p><form className="cs-bank-form" onSubmit={withdraw}><label>Amount (₹)<input required name="amount" type="number" min="100" max={Math.min(100000,(data?.balance??0)/100)} step="0.01"/></label><label>Account holder<input required name="holder" minLength={2} maxLength={100} autoComplete="off"/></label><label>Account number<input required name="account" inputMode="numeric" pattern="[0-9]{9,18}" autoComplete="off"/></label><label>IFSC<input required name="ifsc" pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" autoComplete="off"/></label><button className="cs-primary" disabled={busy||!data}>Request withdrawal <ArrowUpRight size={16}/></button></form><p className="cs-help"><ShieldCheck size={14}/> Bank details are encrypted. Only the super admin can reveal them to process a pending request.</p></section>}
 {admin&&!!data?.wallets.length&&<section className="cs-panel"><h2>Creator balances</h2>{data.wallets.map(w=><div className="cs-ledger-row" key={w.user_id}><strong>{data.people?.find(p=>p.id===w.user_id)?.name??w.user_id}</strong><b>{inr(w.balance_paise)}</b></div>)}</section>}
 <section className="cs-panel"><h2>{admin?'Bank withdrawal queue':'Withdrawal history'}</h2>{!data?.withdrawals.length&&<p>No withdrawals yet.</p>}{data?.withdrawals.map(w=><article className="cs-withdrawal" key={w.id}><div><strong>{inr(w.amount_paise)}</strong><span className={'cs-badge '+w.status}>{w.status}</span></div><p>{admin?(data.people?.find(p=>p.id===w.user_id)?.name??'Creator')+' · ':''}Bank ending {w.bank_last4} · {when(w.created_at)}</p>{w.reference&&<small>{w.reference}</small>}{admin&&w.status==='requested'&&<><button className="cs-link-button" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await community('',{action:'bank-details',id:w.id});setBank({id:w.id,...d.bank});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Reveal bank details (logged)</button>{bank?.id===w.id&&<div className="cs-bank-reveal"><p>{bank.holder}<br/>{bank.account}<br/>{bank.ifsc}</p><button onClick={()=>setBank(null)}>Hide details</button></div>}<form onSubmit={e=>settle(e,w)}><select name="status" aria-label="Withdrawal decision"><option value="paid">Bank transfer completed</option><option value="rejected">Reject and refund wallet</option></select><input name="reference" required minLength={5} maxLength={150} placeholder="Bank transfer reference / rejection reason" aria-label="Transfer reference or reason"/><label className="cs-check"><input type="checkbox" required/>I confirm the transfer was completed externally, or this request should be rejected.</label><button className="cs-primary" disabled={busy}>Record decision</button></form></>}</article>)}</section>
 <section className="cs-panel"><h2>Wallet activity</h2>{!data?.ledger.length&&<p>Your credits and withdrawals will appear here.</p>}{data?.ledger.map(e=><div className="cs-ledger-row" key={e.id}><span className="cs-ledger-icon">{e.amount_paise>0?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><strong>{e.note}</strong><small>{admin?(data.people?.find(p=>p.id===e.user_id)?.name??'Creator')+' · ':''}{when(e.created_at)} · {e.kind}</small></div><b className={e.amount_paise>0?'positive':''}>{e.amount_paise>0?'+':''}{inr(e.amount_paise)}</b></div>)}</section></div>;
}
